export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_FAILURE = "GET_GAMES_FAILURE";

export const GET_SCORE_SUCCESS = "GET_SCORE_SUCCESS";
export const GET_SCORE_FAILURE = "GET_SCORE_FAILURE";

export const GET_GAME_BY_ID_SUCCESS = "GET_GAME_BY_ID_SUCCESS";
export const GET_GAME_BY_ID_FAILURE = "GET_GAME_BY_ID_FAILURE";

export const GET_SCORE_BY_USERNAME_SUCCESS = "GET_SCORE_BY_USERNAME_SUCCESS";
export const GET_SCORE_BY_USERNAME_FAILURE = "GET_SCORE_BY_USERNAME_FAILURE";

export const CREATE_SCORE_SUCCESS = "CREATE_SCORE_SUCCESS";
export const CREATE_SCORE_FAILURE = "CREATE_SCORE_FAILURE";

export const UPDATE_SCORE_SUCCESS = "UPDATE_SCORE_SUCCESS";
export const UPDATE_SCORE_FAILURE = "UPDATE_SCORE_FAILURE";
