export const GET_USERS_SUCCESS="GET_USERS_SUCCESS";
export const GET_USERS_FAILURE="GET_USERS_FAILURE";

export const GET_GAMES_SUCCESS="GET_GAMES_SUCCESS";
export const GET_GAMES_FAILURE="GET_GAMES_FAILURE";